[View in Colaboratory](https://colab.research.google.com/github/lrdshiva/Implementing-Naive-bayes-from-sctach-and-Iris-data-set/blob/master/Naive_Bayes.ipynb)


<a href="https://ibb.co/g0Q5PK"><img src="https://preview.ibb.co/he0uJe/explanation_1.jpg" alt="explanation_1" border="0"></a>
<a href="https://ibb.co/bVGJde"><img src="https://preview.ibb.co/j5W6Wz/explanation_2.jpg" alt="explanation_2" border="0"></a>
<a href="https://ibb.co/fj2kPK"><img src="https://preview.ibb.co/mQGqrz/explanation_3.jpg" alt="explanation_3" border="0"></a>

##**Below is the class that is a direct implementation on the classifier alogn with example of a synthetic data and iris data.**##

In [0]:
import numpy as np
from sklearn.metrics import confusion_matrix

class naive_bayes:
  
  def __init__(self,method = 'Gausian'):
    
    self.classes = {} #dictionary to sort the data class wise.
    self.mean = {}
    self.varience = {}
    self.P_classes = {} # to store prob of the vector belonging to a certain class Ck
    self.pi = 3.14159
    self.P_cl = {} # prob. of occurance of a certain class or prior
    
  def train(self,X,y):
    
    y = y.reshape(-1,1)
    
    self.gaussian(X,y)
  
  def predict(self, X):
    
    y = np.ones((X.shape[0],1))
    
    # take each example
    for n in range(X.shape[0]):
      
      x=X[n,:].reshape(1,-1)
      max_p = 0
      sum_p = 0
      
      
      #select a class and find the coresponding prob
      for i in range(self.unique.shape[0]):
        
        sum_p = 0
        self.P_cl["class"+str(i)] =1
        pcl =   self.P_classes["class"+str(i)]
        
        #find P given each feature in Xn
        for j in range(X.shape[1]):
          
          mean =  self.mean["class"+str(i)][j]
          var =   self.varience["class"+str(i)][j]
          
          #print(self.P_gaussian(x[0,j],mean,var))
          #likelihood
          self.P_cl["class"+str(i)] *= self.P_gaussian(x[0,j],mean,var)
        
        #multiply with prior  
        self.P_cl["class"+str(i)] *= pcl
        
        #evidence
        sum_p += self.P_cl["class"+str(i)]
        
        #print( "prob = " , self.P_cl["class"+str(i)] )
        
        if(self.P_cl["class"+str(i)] > max_p ):
          
          max_p = self.P_cl["class"+str(i)]
          label  = self.unique[i]
      #update and store the label which is most probable among them
      y[n] = label  
    return y
  
  
  # this function finds the unique labels and gathers the data belonging to that class
  def gaussian(self,X,y):
    
    self.unique = np.unique(y)
    
    for i in range(self.unique.shape[0]):
      
      index = np.argwhere(y == self.unique[i])
      
      #print(index,"  d  ")
      
      self.classes["class"+str(i)] = X[index[:,0],:]
      
      self.mean["class"+str(i)] = np.mean(self.classes["class"+str(i)] , axis = 0)
      # note that the varience is sample varience.
      self.varience["class"+str(i)] = np.sum( np.square(self.classes["class"+str(i)] - self.mean["class"+str(i)]) , axis = 0) / (self.classes["class"+str(i)].shape[0]-1)
      # probabilty of occurance of each class from the train data
      self.P_classes["class"+str(i)] = self.classes["class"+str(i)].shape[0]/X.shape[0]
  
  #this function finds the gaussian probability
  def P_gaussian(self,x,mean,var):
    
    A = 1/(((2*self.pi*var)**0.5))
    
    power = np.square(x-mean)/(2*var)
    
    P = A * np.exp(-power)
    
    return P
  
  def score(self,test,predicted):
    
    return confusion_matrix(test, predicted)
  

##Examples to test the algorithm: ##

In [3]:
import numpy as np
D = np.array([[1, 6.0 , 180,	12],
              [1,	5.92,	190,	11],
              [1,	5.58, 170,	12],
              [1,	5.92,	165,	10],
              [2,	5.0 ,	100,	 6],
              [2,	5.5 ,	150,	 8],
              [2,	5.42,	130,	 7],
              [2,	5.75,	150,	 9]])

X = D[:,1:].reshape(8,3)
#print(X)
y = D[:,0].reshape(-1,1)

nb = naive_bayes(method = 'Gausian')
nb.train(X,y)
print(nb.predict(X))
print(nb.predict(np.array([[6,130,8]])))
#print(nb.classes)
#print(nb.mean)
#print(nb.varience)
#print(nb.P_classes)

[[1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]]
[[2.]]


##Application of the algorithm on Iris data set##

In [4]:
from sklearn import datasets

iris_data = datasets.load_iris()
X = iris_data.data
y = iris_data.target.reshape(-1,1)


print(X.shape,"",y.shape)
data =np.concatenate((y,X),axis=1)
#data is shuffled as the data set is sorted
# we are doing so that training is done properly
np.random.shuffle(data)

X_train = data[:20,1:].reshape(-1,4)
y_train = data[:20,0].reshape(-1,1)

X_test = data[21:,1:]
y_test = data[21:,0 ].reshape(-1,1)

(150, 4)  (150, 1)


In [5]:
bayes_iris = naive_bayes(method = 'Gausian')
bayes_iris.train(X_train,y_train)
yp = bayes_iris.predict(X_test)

#for i in range(y_test.shape[0]):
  
  #print("pred = ",yp[i], "  test = ", y_test[i])
  
  
score = bayes_iris.score(y_test,yp)
print("confusion matrix:")
print(score)
print("precision = sum of the diagonal element/total number to test data ")

confusion matrix:
[[45  0  0]
 [ 0 36  5]
 [ 0  2 41]]
precision = sum of the diagonal element/total number to test data


##conclusion##
The naive Bayes classifier is a very efficient classifier as we can see that in the case of Training Iris data sets,  **only 20 samples were taken** and still the classifier could classify with a almost 95% precision. 